### ISSUE TITLE
#001 dll file fails to load

### ISSUE THREAD

**Issue by HombreOso** [HombreOso/NPS_PyQt#1]
Traceback (most recent call last):
  File "T:\014_migration_NPS_to_PyQt\NPS_PyQt\Browser_NPS.py", line 2, in <module>
    from MainWindow_NPS import Ui_MainWindow_NPS
  File "T:\014_migration_NPS_to_PyQt\NPS_PyQt\MainWindow_NPS.py", line 9, in <module>
    from PyQt6 import QtCore, QtGui, QtWidgets
ImportError: DLL load failed while importing QtGui: The specified procedure could not be found

**Comment by HombreOso** [comment]
The issue was resolved by using python 3.10. It is assumed that PyQt6 does not work properly with older versions of python.
